server:
   port: 8080
   servlet:
      context-path: /test
      session:
         timeout: 1440s
   tomcat:
      uri-encoding: UTF-8
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/poff_test?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: sa@123$ys
mybatis-plus:
   configuration:
      map-underscore-to-camel-case: true